pipeline {
  agent none
   stage('last-end') {
      agent {
        docker { image 'openjdk:25-oracle' }
      }
      steps {
        class HelloWorld {
    // Your program begins with a call to main().
    // Prints "Hello, World" to the terminal window.
    public static void main(String args[])
    {
        System.out.println("Hello, World");
    }
}
        javac HelloWorld.java
      }
   }
}
  

